### ISSUE TITLE
frontend-template-application Initial Maintenance

### ISSUE THREAD

**Issue by feanil** [openedx/frontend-template-application#536]
- [x] Github Issues is Enabled
- [x] A `catalog-info.yaml` file exists
- [x] Dependency Update Automation is Enabled
- [ ] [A well-formed README exists.](https://github.com/openedx/frontend-template-application/pull/585)

[Details and links to how-tos.](https://docs.openedx.org/en/latest/developers/how-tos/maintain-a-repo.html)

**Comment by arbrandes** [comment]
I _think_ we're done here.

**Comment by feanil** [comment]
@arbrandes it looks like the readme is missing a bunch of sections from the standard one, is that on purpose?

**Comment by arbrandes** [comment]
Not on purpose, no.  I just didn't check the README against the standard one.  Will do.
